# Generated by Django 3.0.7 on 2020-11-29 09:07

from django.db import migrations


def add_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.all().iterator():
        order_item.price = order_item.product.price * order_item.product.quantity
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(add_price)
    ]

