# Generated by Django 3.0.7 on 2020-11-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20201129_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('DONE', 'Завершенный'), ('IN_PROG', 'Выполняется'), ('CANCEL', 'Отменён')], default='NEW', max_length=15),
        ),
    ]
