# Generated by Django 3.0.7 on 2020-11-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('DONE', 'Завершенный'), ('IN_PROG', 'Выполняется'), ('CANCEL', 'Отменён')], default='NEW', max_length=15, verbose_name='Статус'),
        ),
    ]
