# Generated by Django 3.0.7 on 2020-11-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20201130_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('CASH', 'Наличностью'), ('CARD', 'Электронно')], max_length=4, null=True, verbose_name='способ оплаты'),
        ),
    ]
