# Generated by Django 3.0.7 on 2021-03-27 12:59

from django.db import migrations

import phonenumbers

from django.conf import settings

def format_phonenumber(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all().iterator():
        phonenumber_formatted = phonenumbers.parse(order.phonenumber, 'RU', settings.PHONENUMBER_DB_FORMAT)
        order.phonenumber_new = phonenumber_formatted
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_order_phonenumber_new'),
    ]

    operations = [
        migrations.RunPython(format_phonenumber)
    ]
