# Generated by Django 3.0.7 on 2021-03-28 11:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20210327_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber_new',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='телефон'),
        ),
    ]
