# Generated by Django 3.0.7 on 2021-03-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_remove_order_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phonenumber_new',
            new_name='phonenumber',
        ),
    ]
