# Generated by Django 3.0.7 on 2021-03-28 11:58

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_auto_20210328_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Цена суммарно (цена * количество)', max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='сумма'),
        ),
    ]
