# Generated by Django 3.0.7 on 2021-03-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_auto_20210328_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='amount',
            new_name='total_price',
        ),
    ]
